version: "2.1"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - URL=prashantsolanki.com
      - SUBDOMAINS=www, california,
      - VALIDATION=http
      - DOCKER_MODS=linuxserver/mods:swag-ffmpeg|linuxserver/mods:swag-imagemagick|linuxserver/mods:universal-apprise
      # - CERTPROVIDER= #optional
      # - DNSPLUGIN=cloudflare #optional
      # - PROPAGATION= #optional
      # - DUCKDNSTOKEN= #optional
      # - EMAIL= #optional
      # - ONLY_SUBDOMAINS=false #optional
      # - EXTRA_DOMAINS= #optional
      # - STAGING=false #optional
      # - MAXMINDDB_LICENSE_KEY= #optional
    volumes:
      - ./data/config:/config
    ports:
      - "443:443"
      - "80:80" #optional
    restart: unless-stopped
  # authelia:
  #   image: authelia/authelia:4.21.0
  #   container_name: authelia
  #   environment:
  #     - TZ=Australia/Melbourne
  #   volumes:
  #     - ./data/authelia:/config
  #   restart: unless-stopped
